export default defineAppConfig({
  pages: [
    'pages/auth/login',
    'pages/index/index',
    'pages/task/pool',
    'pages/task/detail',
    'pages/roi/overview',
    'pages/roi/list',
    'pages/roi/detail',
    'pages/club/home',
    'pages/club/announcement-list',
    'pages/club/announcement-detail',
    'pages/club/members',
    'pages/me/profile',
    'pages/me/tasks',
    'pages/me/performance',
    'pages/me/settings',
    'pages/auth/join-status',
  ],
  subPackages: [
    {
      root: 'subpackage-admin',
      pages: [
        'pages/admin/home',
        'pages/admin/task-publish',
        'pages/admin/review',
        'pages/admin/roi-edit',
        'pages/admin/members',
        'pages/admin/join-requests',
        'pages/admin/invites',
        'pages/admin/announcements',
        'pages/admin/club-settings',
        'pages/super/roles',
      ],
    },
  ],
  preloadRule: {
    'pages/index/index': {
      network: 'all',
      packages: ['subpackage-admin'],
    },
  },
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'Rak',
    navigationBarTextStyle: 'black',
    backgroundColor: '#ffffff',
  },
  tabBar: {
    custom: false,
    color: '#737373',
    selectedColor: '#5E6AD2',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/task/pool',
        text: '任务',
        iconPath: 'assets/tabbar/task.png',
        selectedIconPath: 'assets/tabbar/task-active.png',
      },
      {
        pagePath: 'pages/roi/overview',
        text: 'ROI',
        iconPath: 'assets/tabbar/roi.png',
        selectedIconPath: 'assets/tabbar/roi-active.png',
      },
      {
        pagePath: 'pages/club/home',
        text: '团队',
        iconPath: 'assets/tabbar/club.png',
        selectedIconPath: 'assets/tabbar/club-active.png',
      },
      {
        pagePath: 'pages/me/profile',
        text: '我的',
        iconPath: 'assets/tabbar/me.png',
        selectedIconPath: 'assets/tabbar/me-active.png',
      },
    ],
  },
})
